[build]
  publish   = "public"              # Thư mục chứa front-end tĩnh
  functions = "netlify/functions"   # Thư mục chứa các function serverless

[dev]
  command = "netlify dev"           # (tuỳ chọn) để chạy local với netlify-cli
  port    = 8888                    # Frontend + Function local sẽ chạy trên cổng này
